# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 03:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Consultorio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consultorio_name', models.CharField(max_length=64)),
                ('consultorio_number', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doctor_id', models.IntegerField()),
                ('doctor_name', models.CharField(max_length=64)),
                ('doctor_shift', models.CharField(choices=[(b'MAT', b'Matutino'), (b'VES', b'Vespertino'), (b'NOC', b'Nocturno')], default=b'MAT', max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Especialidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('speciality', models.CharField(max_length=64)),
                ('speciality_branch', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paciente_id', models.IntegerField()),
                ('paciente_name', models.CharField(max_length=64)),
                ('paciente_age', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='doctor',
            name='Paciente',
            field=models.ManyToManyField(to='Hospital.Paciente'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='consultorio',
            field=models.ManyToManyField(to='Hospital.Consultorio'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='doctor_speciality',
            field=models.ManyToManyField(to='Hospital.Especialidad'),
        ),
    ]
