# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 03:12
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_area', models.IntegerField()),
                ('nombre_area', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado_Almacen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=64)),
                ('puesto_empleado', models.CharField(choices=[(b'Almacen', b'ALMACEN'), (b'Otro', b'Otro')], default=b'Produccion', max_length=10)),
                ('area_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParraINC.Area')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado_Calidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=64)),
                ('puesto_empleado', models.CharField(choices=[(b'Calidad', b'CALIDAD'), (b'Otro', b'Otro')], default=b'Produccion', max_length=10)),
                ('area_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParraINC.Area')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado_Jefe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=64)),
                ('puesto_empleado', models.CharField(choices=[(b'Jefe_Linea', b'JEFE LINEA'), (b'Otro', b'Otro')], default=b'Produccion', max_length=10)),
                ('pedidos_activos', models.IntegerField()),
                ('area_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParraINC.Area')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Empleado_Produccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_empleado', models.CharField(max_length=64)),
                ('puesto_empleado', models.CharField(choices=[(b'Produccion', b'PRODUCCION'), (b'Otro', b'Otro')], default=b'Produccion', max_length=10)),
                ('area_empleado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParraINC.Area')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pieza', models.IntegerField()),
                ('nombre_pieza', models.CharField(max_length=64)),
                ('precio_unitario', models.FloatField()),
                ('stock', models.IntegerField()),
                ('area_pieza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParraINC.Area')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_pedido', models.IntegerField()),
                ('fecha_entrega', models.DateTimeField(default=django.utils.timezone.now)),
                ('aprobado', models.BooleanField(default=False)),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ParraINC.Area')),
                ('entrega', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ParraINC.Empleado_Almacen')),
                ('jefe_linea', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ParraINC.Empleado_Jefe')),
                ('recibe', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='ParraINC.Empleado_Produccion')),
            ],
        ),
    ]
