# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-25 03:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ParraINC', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pedido',
            old_name='aprobado',
            new_name='terminado',
        ),
        migrations.AddField(
            model_name='pedido',
            name='piezas',
            field=models.ManyToManyField(to='ParraINC.Inventario'),
        ),
    ]
